Repository EikeMB/AppDev2_Project, pull requests merged in 2023-12, with the labels that each got.

#70 implemented add car in create page
  app/src/main/java/com/example/appdev2_assignment2/CRUD/carCrud.kt
  app/src/main/java/com/example/appdev2_assignment2/CRUD/carPartsCrud.kt
  app/src/main/java/com/example/appdev2_assignment2/Car.kt
  app/src/main/java/com/example/appdev2_assignment2/CarPart.kt
  app/src/main/java/com/example/appdev2_assignment2/ViewModels/CarPartViewModel.kt
  app/src/main/java/com/example/appdev2_assignment2/ViewModels/CarViewModel.kt
  app/src/main/java/com/example/appdev2_assignment2/navigation/NavHost.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/CreatePage.kt
Labels: Back end

#76 fixed syncing issue
  app/src/main/java/com/example/appdev2_assignment2/CRUD/carCrud.kt
  app/src/main/java/com/example/appdev2_assignment2/MainActivity.kt
  app/src/main/java/com/example/appdev2_assignment2/ViewModels/CarViewModel.kt
  app/src/main/java/com/example/appdev2_assignment2/auth/Authentication.kt
  app/src/main/java/com/example/appdev2_assignment2/navigation/NavHost.kt
Labels: bug, Back end

#77 Summary page
  .idea/gradle.xml
  app/src/main/java/com/example/appdev2_assignment2/navigation/NavHost.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/CreatePage.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/MainPage.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/SummaryPage.kt
Labels: enhancement, Front end

#78 fixes issue where car would be saved and show on create screen when n…
  app/src/main/java/com/example/appdev2_assignment2/navigation/NavHost.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/AboutPage.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/SummaryPage.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/TopBottomBar.kt
Labels: bug

#79 added a delete button to summary page
  app/src/main/java/com/example/appdev2_assignment2/ui/MainPage.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/SummaryPage.kt
Labels: Back end

#107 changed material theme to be more accessible
  app/src/main/java/com/example/appdev2_assignment2/MainActivity.kt
  app/src/main/java/com/example/appdev2_assignment2/theme/Color.kt
  app/src/main/java/com/example/appdev2_assignment2/theme/Theme.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/CreatePage.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/LoginPage.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/MainPage.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/SignUpPage.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/TopBottomBar.kt
  app/src/main/java/com/example/appdev2_assignment2/ui/UserProfilePage.kt
Labels: enhancement

#122 change title
  app/src/main/java/com/example/car_builder/ui/LoginPage.kt
Labels: Front end, functionality
